default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123
  host: localhost
  port: 5432

development:
  <<: *default
  database:

test:
  <<: *default
  database: avion_things

production:
  <<: *default
  database: avion_things
